version: "3"
services:
  kpi_radio_bot:
    image: kulunchick/kpi-radio:latest
    restart: on-failure
    ports:
      - "6000:6000"
    volumes:
    - ./stuff:/stuff
    - /media/data/MUSIC/:/music
    - /etc/localtime:/etc/localtime:ro # sync time
    depends_on:
      - mopidy
    env_file:
      - .env

  mopidy:
    image: kulunchick/mopidy:latest
    restart: on-failure
    ports:
      - "6680:6680"
    volumes:
      - /media/data/MUSIC/:/music
      - /tmp/pa:/tmp/pa
    environment:
      - PULSE_SERVER=unix:/tmp/pa/pulseaudio.socket
      - PULSE_COOKIE=/tmp/pa/pulseaudio.cookie

  watchtower:
    image: containrrr/watchtower
    restart: on-failure
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--cleanup"
      - "-i"
      - "60"
