name: ci

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push kpi_radio
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:kpi_radio"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/kpi-radio:latest
      -
        name: Build and push mopidy
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mopidy"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/mopidy:latest